#!/usr/bin/env bash

# Parallel version of the compile and test script

set -e

testNumber="01"

# Compiles
mpicc -g -Wall -o gs gs.c -std=c99

# Executes against the test file
mpirun -n 1 ./gs testing/input/input-01 > testing/output/output-$testNumber

cat testing/output/output-$testNumber
