#!/usr/bin/env bash

# Parallel version of the compile and test script

set -e

testNumber="01"
numberOfProcesses="1"

# Loads mpi-module if on CIMS
if [[ "$OSTYPE" == "linux-gnu" ]]; then
	module load openmpi-x86_64
fi

# Compiles
mpicc -g -Wall -o gs gs.c -std=c99

# Executes against the test file
mpirun -n $numberOfProcesses ./gs testing/input/input-$testNumber > testing/output/output-$testNumber

cat testing/output/output-$testNumber
